spring:
  data:
    mongodb:
      database: book-catalog
      auto-index-creation: true
      host: localhost
      port: 27017
  cloud:
    config:
      enabled: off
  redis:
    host: localhost
    port: 6379